version: 2
orbs:
  ruby: circleci/ruby@1.0

docker_build:
  machine:
    image: ubuntu-2004:202201-02
    docker_layer_caching: true

jobs:
  build_test:
    working_directory: ~/my-helper-api
    environment:
      RAILS_ENV: test
      COVERAGE: true
      TZ: "Europe/Istanbul"
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      DATABASE_HOST: 127.0.0.1
      DATABASE_USERNAME: my-helper-api
      DATABASE_PASS: "password"
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: postgres:12.2
        environment:
          POSTGRES_USER: my-helper-api
          POSTGRES_DB: my-helper-api_test
          POSTGRES_PASSWORD: "password"
    parallelism: 4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Postgresql Client
          command: sudo apt install -y postgresql-client || true
      - run:
          name: Bundler 1.17.3
          command: gem install bundler:1.17.3
      - run:
          name: Dockerize
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Db create
          command: bundle exec rake db:create
      - run:
          name: Db Migrate
          command: bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bundle exec rspec --profile 10 --color --out /tmp/test-results/rspec.xml

workflows:
  version: 2
  build:
    jobs:
      - build_test
